from django.db import models

class TempEpisodioAdmision(models.Model):
    id_ingreso = models.IntegerField(db_column='IdIngreso', primary_key=True)
    id_ingreso_origen = models.IntegerField(db_column='IdIngresoOrigen', null=True)
    id_sector = models.IntegerField(db_column='IdSector', null=True)
    txt_fecha_ingreso = models.CharField(db_column='txtFechaIngreso', max_length=12, null=True)
    fecha_ingreso = models.DateTimeField(db_column='FechaIngreso', null=True)
    hora_ingreso = models.DateTimeField(db_column='HoraIngreso', null=True)
    usuario = models.CharField(db_column='Usuario', max_length=50, null=True)
    clave_paciente = models.IntegerField(db_column='ClavePaciente', null=True)
    id_paciente = models.BigIntegerField(db_column='IdPaciente', null=True)
    paciente = models.CharField(db_column='Paciente', max_length=50, null=True)
    id_hcl = models.FloatField(db_column='IdHCL', null=True)
    id_episodio = models.IntegerField(db_column='IdEpisodio', null=True)
    obra_social = models.CharField(db_column='ObraSocial', max_length=50, null=True)
    id_obra_social = models.IntegerField(db_column='IdObraSocial', null=True)
    nro_bono = models.CharField(db_column='NroBono', max_length=50, null=True)
    id_afiliado = models.CharField(db_column='IdAfiliado', max_length=50, null=True)
    datos_transaccion = models.TextField(db_column='DatosTransaccion', null=True)
    calle = models.CharField(db_column='CALLE', max_length=30, null=True)
    localidad = models.CharField(db_column='Localidad', max_length=50, null=True)
    cpostal = models.IntegerField(db_column='CPostal', null=True)
    provincia = models.CharField(db_column='Provincia', max_length=30, null=True)
    medico = models.CharField(db_column='Medico', max_length=50, null=True)
    id_medico = models.IntegerField(db_column='IdMedico', null=True)
    usuario_medico = models.CharField(db_column='UsuarioMedico', max_length=50, null=True)
    matricula = models.IntegerField(db_column='Matricula', null=True)
    id_medico_solicitante = models.IntegerField(db_column='IdMedicoSolicitante', null=True)
    medico_solicitante = models.CharField(db_column='MedicoSolicitante', max_length=80, null=True)
    admision_stamp = models.DateTimeField(db_column='Admision_Stamp', null=True)
    episodio_id_episodio = models.IntegerField(db_column='Episodio_IdEpisodio')
    episodio_id_ingreso = models.IntegerField(db_column='Episodio_IdIngreso', null=True)
    episodio_id_hcl = models.IntegerField(db_column='Episodio_IdHCL', null=True)
    id_tipo_episodio = models.IntegerField(db_column='IdTipoEpisodio', null=True)
    episodio_id_medico = models.IntegerField(db_column='Episodio_IdMedico', null=True)
    episodio_medico = models.CharField(db_column='Episodio_Medico', max_length=50, null=True)
    fecha_atencion = models.DateTimeField(db_column='FechaAtencion', null=True)
    hora_atencion = models.DateTimeField(db_column='HoraAtencion', null=True)
    txt_fecha_hora_atencion = models.CharField(db_column='txtFechaHoraAtencion', max_length=50, null=True)
    episodio_id_medico_solicitante = models.IntegerField(db_column='Episodio_IdMedicoSolicitante', null=True)
    episodio_medico_solicitante = models.CharField(db_column='Episodio_MedicoSolicitante', max_length=80, null=True)
    txt_rtb_hcl = models.TextField(db_column='txtRTBHCL', null=True)
    episodio_stamp = models.CharField(db_column='Episodio_Stamp', max_length=255, null=True)

    class Meta:
        managed = False
        db_table = 'temp_episodios_admision'