# Generated by Django 5.2.5 on 2025-08-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicoAuditor',
        ),
    ]
