# Generated by Django 5.2.5 on 2025-08-28 17:17

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_medicoauditor'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoAuditorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Medico Auditor',
                'verbose_name_plural': 'Medicos Auditores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
