# Generated by Django 5.2.5 on 2025-08-28 17:54

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicoAuditorProxy',
        ),
        migrations.CreateModel(
            name='MedicoAuditor',
            fields=[
            ],
            options={
                'verbose_name': 'Médico Auditor',
                'verbose_name_plural': 'Médicos Auditores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
