# Generated by Django 5.2.5 on 2025-08-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioMedico',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_medico', models.FloatField(default=0)),
                ('alcance', models.IntegerField(default=0)),
                ('n_matricula', models.IntegerField(default=0)),
                ('pregunta', models.CharField(blank=True, max_length=50, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('stamp', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'UsuariosMedicos',
                'indexes': [models.Index(fields=['id_medico'], name='UsuariosMed_id_medi_c169ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id_episodio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ingreso', models.IntegerField(default=0)),
                ('id_hcl', models.IntegerField(default=0)),
                ('id_tipo_episodio', models.IntegerField(default=0)),
                ('id_capitulo', models.IntegerField(default=0)),
                ('id_medico', models.IntegerField(default=0)),
                ('medico', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('txt_fecha_hora_atencion', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_de_consulta', models.CharField(blank=True, default='', max_length=50)),
                ('sintomas_breve', models.TextField(blank=True, null=True)),
                ('tratamiento_previo', models.TextField(blank=True, default='')),
                ('diagnostico_presuntivo', models.CharField(blank=True, default='', max_length=255)),
                ('cie10_diagnostico_presuntivo', models.CharField(blank=True, default='', max_length=10)),
                ('tratamiento', models.TextField(blank=True, default='')),
                ('stamp', models.CharField(blank=True, default='current_timestamp()', max_length=255)),
                ('paciente', models.ForeignKey(db_column='IdPaciente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.paciente')),
                ('usuario', models.ForeignKey(db_column='Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.usuariomedico')),
            ],
            options={
                'db_table': 'TblEpisodios',
                'indexes': [models.Index(fields=['id_capitulo'], name='TblEpisodio_id_capi_8a204b_idx'), models.Index(fields=['id_episodio'], name='TblEpisodio_id_epis_d2b241_idx'), models.Index(fields=['id_ingreso'], name='TblEpisodio_id_ingr_7ea8b5_idx'), models.Index(fields=['id_medico'], name='TblEpisodio_id_medi_dfa9e0_idx')],
            },
        ),
    ]
