# Generated by Django 5.2.5 on 2025-08-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomedico',
            name='datos_medico',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
