# Generated by Django 5.2.5 on 2025-08-30 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_usuariomedico_datos_medico'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='episodio',
            name='TblEpisodio_id_epis_d2b241_idx',
        ),
        migrations.RemoveIndex(
            model_name='episodio',
            name='TblEpisodio_id_medi_dfa9e0_idx',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='id_medico',
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='episodio',
            name='id_episodio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='medico',
            field=models.ForeignKey(db_column='Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.usuariomedico'),
        ),
        migrations.AlterField(
            model_name='usuariomedico',
            name='id_medico',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddIndex(
            model_name='episodio',
            index=models.Index(fields=['medico'], name='TblEpisodio_Usuario_1c153c_idx'),
        ),
        migrations.AddIndex(
            model_name='episodio',
            index=models.Index(fields=['paciente'], name='TblEpisodio_IdPacie_84c2cf_idx'),
        ),
    ]
